### ISSUE TITLE
java.lang.NullPointerException in projections.analysis.Analysis.hasSumFiles

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/projections#55]
*Original author: Thomas Quinn*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1910*

---
I'm trying to analyze some projections traces from ChaNGa (linked with -tracemode projections), and trying to open an sts file gives:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at projections.analysis.Analysis.hasSumFiles(Analysis.java:945)
        at projections.analysis.Analysis.hasSummaryData(Analysis.java:592)
        at projections.gui.MainWindow$2.done(MainWindow.java:279)
        at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
        at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
        at javax.swing.Timer.fireActionPerformed(Timer.java:313)
        at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pplimport** [comment]
*Original author: Thomas Quinn*
*Original date: 2018-05-15 00:49:54*

---
I think I found the problem: the sts file has a line:
CHARE 50 CkCacheManager<CmiUInt8 > -1
which projections can't parse because of the space.

I'm guessing this has to do with changes to the charm++ compiler.

**Comment by rbuch** [comment]
*Original date: 2018-05-15 16:48:47*

---
The sts file is correct, but it should have failed earlier, in fact. What version is reported in the sts file (it should be on the second line of the sts file)?

I recently modified the version in Charm and Projections to version 9.0 to better support IDs for chare arrays of dimension greater than 3. Support for the new files was added in Projections commit 84a995a5e9bac9ac6549590bcc57ae12f1378f2e. If you're using a version older than that, it should complain about a version mismatch and exit rather than causing a NullPointerException.

**Comment by rbuch** [comment]
*Original date: 2018-05-15 16:50:39*

---
Oh, wait, sorry, I didn't see the space between "CmiUInt8" and ">". That does indeed seem erroneous and likely due to some change in Charm. I'll take a look.

**Comment by pplimport** [comment]
*Original author: Thomas Quinn*
*Original date: 2018-05-15 18:40:56*

---
The sts file is version 9.  I deleted the space by hand, and projections works.

**Comment by rbuch** [comment]
*Original date: 2018-05-15 19:21:54*

---
~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4176/~~ https://github.com/UIUC-PPL/charm/commit/27801da2a9b25b9108320187c75f8b997b828999
https://charm.cs.illinois.edu/gerrit/#/c/projections/+/4177/
